services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - api
  api:
    build: ./backend
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/blacklist_db
      - REDIS_URL=redis://redis:6379/0
      - API_KEY=admin
      - ALLOWED_ORIGINS=http://localhost:8080,http://localhost:3000
    depends_on:
      - db
      - redis
  worker:
    build: ./backend
    command: celery -A app.worker worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/blacklist_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - db
  beat:
    build: ./backend
    command: celery -A app.worker beat --loglevel=info
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/blacklist_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - db
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=blacklist_db
  redis:
    image: redis:7
